# traefik.rbac.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-deployment
subjects:
  - kind: ServiceAccount
    name: traefik-deployment
    namespace: kube-public
