##
## EPITECH PROJECT, 2018
## 301dannon
## File description:
## Makefile
##

NAME	=	301dannon

all: $(NAME)

$(NAME):
	cp 301dannon.py $(NAME)
	chmod 755 $(NAME)

clean:
	rm -rf __pycache__

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: re fclean all
