##
## EPITECH PROJECT, 2018
## 309pollution
## File description:
## Makefile
##

NAME	=	309pollution

all: $(NAME)

$(NAME):
	cp 309pollution.py $(NAME)
	chmod 755 $(NAME)

clean:
	rm -rf __pycache__

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: re fclean all
