##
## EPITECH PROJECT, 2018
## 308reedpipes
## File description:
## Makefile
##

NAME	=	308reedpipes

all: $(NAME)

$(NAME):
	cp 308reedpipes.py $(NAME)
	chmod 755 $(NAME)

clean:
	rm -rf __pycache__

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: re fclean all
