##
## EPITECH PROJECT, 2018
## 305construction
## File description:
## Makefile
##

NAME	=	305construction

all: $(NAME)

$(NAME):
	cp 305construction.py $(NAME)
	chmod 755 $(NAME)

clean:
	rm -rf __pycache__

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: re fclean all
