##
## EPITECH PROJECT, 2018
## 209poll
## File description:
## Makefile
##

NAME	=	209poll

all: $(NAME)

$(NAME):
	cp 209poll.py $(NAME)
	chmod 755 $(NAME)

clean:
	rm -rf __pycache__

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: re fclean all
