##
## EPITECH PROJECT, 2018
## 302separation
## File description:
## Makefile
##

NAME	=	302separation

all: $(NAME)

$(NAME):
	cp 302separation.py $(NAME)
	chmod 755 $(NAME)

clean:
	rm -rf __pycache__

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: re fclean all
