##
## EPITECH PROJECT, 2018
## 206neutrinos
## File description:
## Makefile
##

NAME	=	206neutrinos

all: $(NAME)

$(NAME):
	cp 206neutrinos.py $(NAME)
	chmod 755 $(NAME)

clean:
	rm -rf __pycache__

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: re fclean all
